### ISSUE TITLE
Half-equirectangular support

### ISSUE THREAD

**Issue by xnrfn** [androclassic/SphereSnap#1]
Feature request, ability to output to half equirectangular (180x180).

I am trying to add it myself but i am way over my head and am using copilot/gpt4 for complex tasks. still I will try to send a pull request if i get it working somehow.

**Comment by androclassic** [comment]
a half equirectangular image can be achieved by just passing cropping a full equirectangular image. So you can output into an equirectangular image and than crop it. Can you describe in more detail what exactly you want to achieve?  I am pretty sure there is already a way to do it with the current functionalities .

**Comment by xnrfn** [comment]
i'm looking to create perspective images from sections of half euqirectangular images (based on rough object detection). I then want to convert those to perspective images. This part I've managed to implement so far. Not much code to add, just a new imageprojectiontype and some half-equirect equivalents of equirectangular functions. I did struggle a long time with createFromPoint, I could not get it to work, but creating a spheresnap with a correct orientation_quat (-yaw, -pitch, -90) does the trick for now. 

Then I want to alter the perspective images (annotate the object for example) and then reinsert it into the half euqirectangular frame. This part I'm still working on. I don't think this functionality exists yet, but i think i can get there with merge_multiple_snaps.

I thought to use spheresnap because it solves the core problem for various forms of projection (fisheye, equirect, distorted etc) all at once. But i've no idea if I'm doing it the right way; i'll leave the code review up to you once i wrap this up. I'm on holidays though so it'll be a bit before i submit it.

**Comment by androclassic** [comment]
https://github.com/androclassic/SphereSnap/commit/703bfb99486bb7b125e52203bdfcb16ea2c28fbf

**Comment by androclassic** [comment]
This should do the trick for you, I have added a sample notebook where I demonstrate how to create a perspective image from point using half-equirectangular projection

**Comment by xnrfn** [comment]
Sorry for not replying sooner. Just getting around to testing this. A few pointers:

1. Notebook fails with:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 tv_img = rpr.equi2tv(equi_blend, np.identity(3), (1000,1000), (90,90), 10, 2)
      2 show_img(tv_img)

NameError: name 'equi_blend' is not defined
```

Looks like `equi_blend` should be `equi_photo`?

2. I had basically the same code but I had `coor_y = (-theta / np.pi + 0.5) * h - 0.5` (negative theta). I assume this is because i had some other error in additional functions i added (pinhole2hequi, xyz_to_hequirect).

In any case, what I still don't see is how you would take the generated `persp_img`, manipulate that (e.g. add red square over the blue dot in the `persp_img`), and then integrate it back into the spheresnap (to then generate a cubemap/halfequi/equirectangular image from). That's why I spent time on pinhole2hequi, but I might be on the wrong track here.

Is that possible with the current code?

**Comment by xnrfn** [comment]
OK, so I have that also figured out. I am just stuck on one final point.

How do I load an existing half equirectangular image using a SnapConfig so that I can use it in a merge_multiple_snaps? No matter what I try, I can't seem to load it without it distorting. E.g.:

```
perspective_image_modified = ...

perspective_image_config = SnapConfig(
    orientation_quat=rotation_quat, 
    out_hw=(hequirect_front.shape[1], hequirect_front.shape[0]),
    out_fov_deg=adjusted_fov,
    source_img_hw=(hequirect_front.shape[1],hequirect_front.shape[0]),
    source_img_fov_deg=(180,180), 
    source_img_type=ImageProjectionType.HALF_EQUI
)


perspective_image_snap = SphereSnap(perspective_image_config)

# define a spheresnap for loading the half equi original image

rotation_quat = R.from_euler("yxz", [0, 0, 0], degrees=True).as_quat()
orig_snap_config = SnapConfig(
    orientation_quat=rotation_quat, 
    out_hw=(hequirect_front.shape[1], hequirect_front.shape[0]),
    out_fov_deg=(180,180),
    source_img_hw=(hequirect_front.shape[1],hequirect_front.shape[0]),
    source_img_fov_deg=(180,180), 
    source_img_type=ImageProjectionType.HALF_EQUI
)

orig_snap_obj = SphereSnap(orig_snap_config)

# merge the modified image into the original
modded_hequirect_front = SphereSnap.merge_multiple_snaps(hequirect_hw, [orig_snap_obj, perspective_image_snap], [hequirect_front,perspective_image_modified], target_type=ImageProjectionType.EQUI, merge_method="last")
```

The modified perspective image is fine. But the original `hequirect_front` image is fully distorted and does not span the entire image as you would expect it to.

AFAICT the only way to parse the half equirectangular image is to first create cubemaps from it, and then pass those all through merge_multiple_snaps. Is there no way to do that in one go? Should be much faster then?

**Comment by xnrfn** [comment]
Hi again,

I ran into this:
```
  File "/home/xnrfn/src/vrm/vrmerger.py", line 141, in merge_frame_thread
    reconstructed_hequi = SphereSnap.merge_multiple_snaps((vr_height, half_width),
  File "/home/xnrfn/src/vrm/sphere_snap/sphere_snap.py", line 353, in merge_multiple_snaps
    colors = snap_img[view_coor_y, view_coor_x] 
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 256
```

What I gather is that it has something to do with np.nan being set on the wrong (int) np array, but I'm not quite sure why it happens. It only happens to a small percentage of images I am calling this with, and there's no real difference between the ones that work and the ones that do not.

Edit: FWIW i fixed it like this:

```
            # strip nan from view_coors before converting to int
            view_coors_safe = np.nan_to_num(view_coors, copy=True, nan=0.0)

            # sample all pixel values from the view image
            view_coor_x, view_coor_y = np.split(view_coors_safe.astype(int), 2, axis=-1)
            ...
```
            
Not sure if that's the right way, but does seem to fix the error.
